environment:
  name: prod
spring:
  datasource:
    url: jdbc:postgresql://dpg-crhk83btq21c73futje0-a:5432/money_tracker_8ifs
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver