environment:
  name: prod
spring:
  datasource:
    url: jdbc:postgresql://dpg-crhk83btq21c73futje0-a:5432/money_tracker_8ifs
    username: root
    password: lBjz63QTQlR22KAVjYGuMPc1AVrCYYcL
    driver-class-name: org.postgresql.Driver